# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - rb10_source_controller
    - rb10_detector_controller

  rb10_source_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - base_source
      - shoulder_source
      - elbow_source
      - wrist1_source
      - wrist2_source
      - wrist3_source
  rb10_detector_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - base_detector
      - shoulder_detector
      - elbow_detector
      - wrist1_detector
      - wrist2_detector
      - wrist3_detector