# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    rb10_source_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    rb10_detector_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

rb10_source_controller:
  ros__parameters:
    joints:
      - base_source
      - shoulder_source
      - elbow_source
      - wrist1_source
      - wrist2_source
      - wrist3_source
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
rb10_detector_controller:
  ros__parameters:
    joints:
      - base_detector
      - shoulder_detector
      - elbow_detector
      - wrist1_detector
      - wrist2_detector
      - wrist3_detector
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity