from abc import ABC, abstractmethod
from typing import List
import numpy as np

class OptimizerBase(ABC):
    def __init__(self):
        pass

    @abstractmethod
    def optimize(self, path: List[np.ndarray], planner) -> List[np.ndarray]:
        """
        Optimize the given path.
        
        Args:
            path (List[np.ndarray]): The initial path generated by the planner.
            planner (PlannerBase): The planner instance, used for collision checking/feasibility.
            
        Returns:
            List[np.ndarray]: The optimized path.
        """
        pass
